version: "3.9"
 
services:
  frontend:
    build:
      context: ..
      dockerfile: hagameonline/Dockerfile
    container_name: hagameonline_frontend
    restart: always
    ports:
      - "80:80"
 