version: "3.9"

services:
  frontend:
    build:
      context: ..
      dockerfile: hagameonline/Dockerfile
    container_name: hagameonline_frontend
    volumes:
      - /firebase.json:/firebase.json:ro
    restart: always
    expose:
      - "4321"

  nginx:
    image: nginx:stable-alpine
    container_name: hagameonline_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend

networks:
  default:
    name: hagameonline_net